#!/usr/bin/env bash
# Install and configure HAProxy load balancer on your lb-01 server.
sudo apt-get update 
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get install haproxy=2.0.\*

# Code to enable load balancer
sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy

# Code to configure my load balancer with my web servers
server_config=\
"
frontend  load_balancer
        bind *:80
        mode http
        default_backend web_servers
backend web_server
        balance roundrobin
        server 185362-web-01 100.24.240.118:80 check
        server 185362-web-02 18.207.234.203:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

#Restart HAproxy
sudo service haproxy restart
