#!/bin/bash
echo "I will be using this current directory as my working directory, so cool! I love ALX! ALX program has been so impactful since commencement! I have been able push myself and also work with great minds from across the country and beyond! I am so grateful for this opportunity!"
