#!/usr/bin/env bash
# install ufw
sudo apt install ufw

# setting up default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allowing incoming traffic for ssh, http and https/ssl
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# enabling ufw
sudo ufw enable
