#!/usr/bin/env bash
# This bash script runs nginx as nginx user

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# changes to port 8080

sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# grant permission to read and write the conf 

sudo chmod 644 /etc/nginx/nginx.conf

# kill apache2 process so it doesnt interfere with nginx

sudo pkill apache2

# start nginx with the new user

sudo -u nginx service nginx start
